### ISSUE TITLE
Deployment\ServerException

### ISSUE THREAD

**Issue by aleswita** [dg/ftp-deployment#117]
Version: 3.1.0
### Bug Description
I'm trying to use this library, but every time, when can I try to deploy files to FTP server, tool was throws an exception on same file/dir.

Any idea what is wrong?

```
...
( 5483 of 10212) /vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Shared/Drawing.php
( 5484 of 10212) /vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Shared/Escher/
( 5485 of 10212) /vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Shared/Escher/DgContainer/
( 5486 of 10212) /vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Shared/Escher/DgContainer/SpgrContainer/
( 5487 of 10212) /vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Shared/Escher/DgContainer/SpgrContainer/SpContainer.php
( 5488 of 10212) /vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Shared/Escher/DgContainer/SpgrContainer.php
( 5489 of 10212) /vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Shared/Escher/DgContainer.php
( 5490 of 10212) /vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Shared/Escher/DggContainer/
( 5491 of 10212) /vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Shared/Escher/DggContainer/BstoreContainer/
Error: "/sub/__ales__test__" is the current directory in C:\xampp_72\htdocs\ftp-deployment\src\Deployment\CliRunner.php:181

Deployment\ServerException: "/sub/__ales__test__" is the current directory in C:\xampp_72\htdocs\ftp-deployment\src\Deployment\CliRunner.php:181
Stack trace:
#0 [internal function]: Deployment\CliRunner->Deployment\{closure}(2, '"/sub/__ales__t...', 'C:\\xampp_72\\htd...', 198, Array)
#1 C:\xampp_72\htdocs\ftp-deployment\src\Deployment\FtpServer.php(198): ftp_chdir(Resource id #14768, '/sub/__ales__te...')
#2 C:\xampp_72\htdocs\ftp-deployment\src\Deployment\FtpServer.php(165): Deployment\FtpServer->isDir('/sub/__ales__te...')
#3 C:\xampp_72\htdocs\ftp-deployment\src\Deployment\Deployer.php(243): Deployment\FtpServer->createDir('/sub/__ales__te...')
#4 C:\xampp_72\htdocs\ftp-deployment\src\Deployment\Deployer.php(146): Deployment\Deployer->uploadPaths(Array)
#5 C:\xampp_72\htdocs\ftp-deployment\src\Deployment\CliRunner.php(96): Deployment\Deployer->deploy()
#6 C:\xampp_72\htdocs\ftp-deployment\src\deployment.php(26): Deployment\CliRunner->run()
#7 C:\xampp_72\htdocs\ftp-deployment\deployment(3): require('C:\\xampp_72\\htd...')
#8 {main}

**Comment by aleswita** [comment]
Seems that connection issue in my work..
